config/routes.rb
VotaPrato::Application.routes.draw do

  
  devise_for :users

  resources :comentarios

  resources :qualificacoes

  resources :clientes
  root :to => "restaurantes#index"

  match ':controller(/:action(/:id))(.:format)'
  match 'inicio' => 'restaurantes#index'
  

  

end

app/models/cliente.rb
#encoding: utf-8

class Cliente < ActiveRecord::Base
  attr_accessible :nome, :idade

  validates_presence_of :nome, message: " - deve ser preenchido"
  validates_uniqueness_of :nome, message: " - nome já cadastrado"
  validates_numericality_of :idade, greater_than: 0, less_than: 100, message: " - deve ser um número entre 0 e 100"

  has_many :qualificacoes

end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
before_filter :authenticate_user!, :except => [:index,:show]

  respond_to :html, :xml
  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.order("nome").page(params['page']).per(5)

   respond_with @clientes
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
    @cliente = Cliente.find(params[:id])

    respond_with @cliente
  end

  # GET /clientes/new
  # GET /clientes/new.json
  def new
    @cliente = Cliente.new

    respond_with @cliente
  end

  # GET /clientes/1/edit
  def edit
    @cliente = Cliente.find(params[:id])
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(params[:cliente])

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render json: @cliente, status: :created, location: @cliente }
      else
        format.html { render action: "new" }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clientes/1
  # PUT /clientes/1.json
  def update
    @cliente = Cliente.find(params[:id])

    respond_to do |format|
      if @cliente.update_attributes(params[:cliente])
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente = Cliente.find(params[:id])
    @cliente.destroy

    respond_to do |format|
      format.html { redirect_to clientes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
<%= form_for(@cliente) do |f| %>
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% @cliente.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <font color="darkgrey" size="6"><%= f.label :nome %><br /></font>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <font color="darkgrey" size="6"><%= f.label :idade %><br /></font>
    <%= f.number_field :idade %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1 class="titulo" align="center"><font color="#9B1C26">Editando Cliente</font></h1>

<table align="center" class="titulo2">
	<tr>
		<td align="center">
			<font size="6">
<%= render 'form' %>
			</font>
		</td>
	</tr>
</table>

<table align="center" class="titulo2">
	<td>
		<font size="6">
<%= link_to 'Mostrar', @cliente %> |
<%= link_to 'Voltar', clientes_path %>
		</font>
	</td>
</table>

app/views/clientes/index.html.erb
<h1 align="center" class="titulo"><font color="#9B1C26">Clientes</font></h1>

<table class="tabelacor" align="center">
  <br>
  <br>
  <br>

  <tr>
    <th><font color="#9B1C26" size="6">Nome</font></th>
    <th><font color="#9B1C26" size="6">Idade</font></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clientes.each do |cliente| %>
  <tr>
    <td><font color="darkgrey" size="6"><%= cliente.nome %></font></td>
    <td><font color="darkgrey" size="6"><%= cliente.idade %></font></td>
    <td><font color="darkgrey" size="6"><%= link_to 'Mostrar', cliente %></font></td>
    <td><font color="darkgrey" size="6"><%= link_to 'Editar', edit_cliente_path(cliente) %></font></td>
    

    
  </tr>
<% end %>
</table>

<br>
<br>
<br>
<br>

<y align="center" class="fonte">
<center><%= paginate @clientes %>
</y>


<br>
<br>
<br>
<br>
<br>
<br>

<font class="novo" size="6">
  <!--<%= link_to 'Novo', action: 'new' %>-->

<a class="bt" href="http://localhost:3000/clientes/new" title="Novo Cliente"><font color="white">Novo Cliente</font></a>  
</font>

app/views/clientes/new.html.erb
<h1 align="center" class="titulo"><font color="#9B1C26">New cliente</font></h1>

<br>
<br>

<table align="center">
	<tr>
		<td align="center">
			<font size="6">
<%= render 'form' %>
			</font>
		</td>
	</tr>
</table>

<br>
<br>
<br>

<table align="center">
	<td>
		<font size="6">
<%= link_to 'Voltar', clientes_path %>
		</font>
	</td>
</table>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<table align="center" class="titulo2">
	<tr>
		<td align="center">
			<font size="6">
<p>
  <b><font color="#9B1C26">Nome:</font></b>
  <font color="grey"><%= @cliente.nome %></font>
</p>

<p>
  <b><font color="#9B1C26">Idade:</font></b>
  	<font color="grey"><%= @cliente.idade %></font>
</p>

			</font>
		</td>
	</tr>
</table>
	
<table align="center" class="titulo2">
	<tr>
		<td align="center">
			<font size="6">
<%= link_to "Nova qualificação", :controller => "qualificacoes", :action => "new", :cliente => @cliente %>
			</font>
		</td>
	</tr>
</table>

<table align="center" class="titulo2">
	<td align="center">
		<font size="6">
<%= link_to 'Editar', edit_cliente_path(@cliente) %> |
<%= link_to 'Voltar', clientes_path %>
		</font>
	</td>
</table>