config/routes.rb
VotaPrato::Application.routes.draw do

  
  devise_for :users

  resources :comentarios

  resources :qualificacoes

  resources :clientes
  root :to => "restaurantes#index"

  match ':controller(/:action(/:id))(.:format)'
  match 'inicio' => 'restaurantes#index'
  

  

end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
attr_accessible :conteudo, :comentavel_id, :comentavel_type
belongs_to :comentavel, polymorphic: true
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController

  before_filter :authenticate_user!, :except => [:index,:show]
  
  # GET /comentarios
  # GET /comentarios.json
  def index
    @comentarios = Comentario.order("conteudo").page(params['page']).per(5)


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comentarios }
    end
  end

  # GET /comentarios/1
  # GET /comentarios/1.json
  def show
    @comentario = Comentario.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comentario }
    end
  end

  # GET /comentarios/new
  # GET /comentarios/new.json
  def new
    @comentario = Comentario.new

    respond_to do |format|
      format.html #{redirect_to @comentario} # new.html.erb
      format.json { render json: @comentario }
    end
  end

  # GET /comentarios/1/edit
  def edit
    @comentario = Comentario.find(params[:id])
  end

  # POST /comentarios
  # POST /comentarios.json
  def create
    @comentario = Comentario.new(params[:comentario])
    respond_to do |format|
      @comentario.save
      format.html {redirect_to @comentario, notice: 'Comentario postado'}
      format.xml {render :xml => @comentario, :status => :created, :location => @comentario }
      format.js
      
        #format.html { render action: "new" }
        #format.json { render json: @comentario.errors, status: :unprocessable_entity }

      
    end
  end

  # PUT /comentarios/1
  # PUT /comentarios/1.json
  def update
    @comentario = Comentario.find(params[:id])

    respond_to do |format|
      if @comentario.update_attributes(params[:comentario])
        format.html { redirect_to @comentario, notice: 'Comentario was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1
  # DELETE /comentarios/1.json
  def destroy
    @comentario = Comentario.find(params[:id])
    @comentario.destroy
    respond_to do |format|
      format.html {redirect_to @comentario, notice: 'Comentario deletado'}
      format.xml {head :ok }
      format.js {head :ok }
      
    end
  end
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
	
	def comentarios(comentavel)
		comentarios= "<div id='comentarios'>"
		comentarios << "<h3>Comentarios</h3>"
		comentarios << render(comentavel.comentarios) unless comentavel.comentarios.empty?
		comentarios << "</div>"
		raw comentarios
	end

end

app/views/comentarios/_comentario.html.erb
<p id="comentario_<%= comentario.id %>">
	<%= comentario.conteudo %> -
	<%= link_to '(remover)', comentario, :method => :delete,
	:remote => true, 
	:id => "remove_comentario_#{comentario.id}" %>
</p>

<%= content_for :js do %>
	$('#remove_comentario_<%=comentario.id%>').bind('ajax:success',
		function(xhr, result){
			$('#comentario_<%=comentario.id%>').remove();
		}
	);
<% end %>

app/views/comentarios/_form.html.erb
<%= form_for(@comentario) do |f| %>
  <% if @comentario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul>
      <% @comentario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" size="6">
    <font color="darkgrey"><%= f.label :conteudo %><br /></font>
    <%= f.text_area :conteudo %>
  </div>


  <div class="field" size="6">
    <font color="darkgrey"><%= f.label :comentavel_id %><br /></font>
    <%= f.number_field :comentavel_id %>
  </div>


  <div class="field" size="6">
   <font color="darkgrey"> <%= f.label :comentavel_type %><br /></font>
    <%= f.text_field :comentavel_type %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comentarios/_novo_comentario.html.erb
<div id='novo_comentario'>
	<a href="#" onclick="$('#novo_comentario').children().toggle();">
		Novo comentario 
	</a>

	<div id="form_comentario" style="display: none;">
		<%= form_for Comentario.new, :remote => true do |f| %>
		<%= hidden_field :comentario, :comentavel_id, :value => comentavel.id %>
		<%= hidden_field :comentario, :comentavel_type, :value => comentavel.class %>

	<div class="field">
		<%= f.label 'conteudo' %></br>
		<%= f.text_area 'conteudo' %>
	</div>

	<div class="actions">
		<%= f.submit %>
		<a href="#" onclick="$('#'novo_comentario').children().toggle();">
			Cancelar
		</a>

	</div>
   <%end%>
  </div>
 </div>


<%content_for :js do%>
$('#form_comentario').bind('ajax:complete', function(xhr, result){
	$('#comentarios').html(result.responseText);
	$('#form_comentario textarea').val("")
	$('#form_comentario').hide();
	$('#novo_comentario > a').show();
});
<%end%>

app/views/comentarios/create.js.erb
<%= render(:partial => "comentarios/comentario", :collection => @comentario.comentavel.comentarios) %>

app/views/comentarios/edit.html.erb
<h1 class="titulo" align=center><font color="#9B1C26">Editar Comentário</font></h1>

<table align="center" class="titulo2">
	<tr>
		<td align="center">
			<font size="6">
<%= render 'form' %>
			</font>
		</td>
	</tr>
</table>

<table align="center" class="titulo2">
	<td align="center">
		<font size="6">
<%= link_to 'Mostrar', @comentario %> |
<%= link_to 'Voltar', comentarios_path %>
		</font>
	</td>
</table>

app/views/comentarios/index.html.erb
<h1 size="6" align="center" class="titulo"><font color="#9B1C26">Lista de Comentarios<font></h1>

<table align="center" width="80%">

  <br>
  <br>
  <br>

  <tr>
    <th><font size="6" color="#9B1C26">Conteudo</font></th>
    <th><font size="6" color="#9B1C26">ID Coment&aacute;rio</font></th>
    <th colspan="3"><font color="#9B1C26" size="6">Controle de Comentários</font></th>
  </tr>

<% @comentarios.each do |comentario| %>
  <tr align="center">

    
    <td><font size="6" color="darkgrey"><%= comentario.conteudo %></font></td>
    <td><font size="6" color="darkgrey"><%= comentario.comentavel_id %></font></td>
    <td><font size="6" color="darkgrey"><%= comentario.comentavel_type %></font></td>
    <td><font size="6" color="darkgrey"><%= link_to 'Mostrar', comentario %></font></td>
    <td><font size="6" color="darkgrey"><%= link_to 'Editar', edit_comentario_path(comentario) %></font></td>
    <td><font size="6" color="darkgrey"><%= link_to 'Remover', comentario, method: :delete, data: { confirm: 'Você tem certeza?' } %></font></td>
  </tr>
<% end %>
</table>

<br>
<br>
<br>
<br>


<y align="center" class="fonte">
<center><%= paginate @comentarios %>
</y>

<br>
<br>
<br>

<br>
<br>
<br>



<font class="novo" size="6">
  <!--<%= link_to 'Novo', action: 'new' %>-->

<a class="bt" href="http://localhost:3000/comentarios/new" title="Novo Comentário">
  <font color="white">Novo Comentário</font>
</a>  
</font>

app/views/comentarios/new.html.erb
<h1 align="center" class="titulo"><font color="#9B1C26">Novo Comentário</font></h1>

<table align="center" class="titulo2">
	<tr>
		<td align="center">
			<font size="6">
<%= render 'form' %>
			</font>
		</td>
	</tr>
</table>

<br>

<table align="center"  class="titulo2">
	<td>
		<font size="6">
<%= link_to 'Voltar', comentarios_path %>
		</font>
	</td>
</table>	

app/views/comentarios/show.html.erb
<p id="notice"><%= notice %></p>
<table align="center" class="titulo">
	<tr>
		<td>
			<font size="6">
<p>
  <b><font color="#9B1C26">Comet&aacute;rio:</font></b>
  <font color="grey"><%= @comentario.conteudo %></font>
</p>

<p>
  <b><font color="#9B1C26">Nome do Restaurante:</font></b>
  <font color="grey"><%= @comentario.comentavel_id %></font>
</p>

<p>
  <b><font color="#9B1C26">Tipo de Coment&aacute;rio:</font></b>
  <font color="grey"><%= @comentario.comentavel_type %></font>
</p>
			</font>
		</td>
	</tr>
</table>

<table align="center" class="titulo2">
	<td>
		<font size="6">
<%= link_to 'Editar', edit_comentario_path(@comentario) %> |
<%= link_to 'Voltar', comentarios_path %>
		</font>
	</td>
</table>