config/routes.rb
VotaPrato::Application.routes.draw do

  
  devise_for :users

  resources :comentarios

  resources :qualificacoes

  resources :clientes
  root :to => "restaurantes#index"

  match ':controller(/:action(/:id))(.:format)'
  match 'inicio' => 'restaurantes#index'
  

  

end

app/controllers/qualificacoes_controller.rb
class QualificacoesController < ApplicationController

  before_filter :authenticate_user!, :except => [:index,:show]

  
  # GET /qualificacoes
  # GET /qualificacoes.json
  def index
    @qualificacoes = Qualificacao.order("restaurante_id").page(params['page']).per(5)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @qualificacoes }
    end
  end

  # GET /qualificacoes/1
  # GET /qualificacoes/1.json
  def show
    @qualificacao = Qualificacao.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @qualificacao }
    end
  end

  # GET /qualificacoes/new
  # GET /qualificacoes/new.json
  def new
    @qualificacao = Qualificacao.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @qualificacao }
    end
  end

  # GET /qualificacoes/1/edit
  def edit
    @qualificacao = Qualificacao.find(params[:id])
  end

  # POST /qualificacoes
  # POST /qualificacoes.json
  def create
    @qualificacao = Qualificacao.new(params[:qualificacao])

    respond_to do |format|
      if @qualificacao.save
        format.html { redirect_to @qualificacao, notice: 'Qualificacao was successfully created.' }
        format.json { render json: @qualificacao, status: :created, location: @qualificacao }
      else
        format.html { render action: "new" }
        format.json { render json: @qualificacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /qualificacoes/1
  # PUT /qualificacoes/1.json
  def update
    @qualificacao = Qualificacao.find(params[:id])

    respond_to do |format|
      if @qualificacao.update_attributes(params[:qualificacao])
        format.html { redirect_to @qualificacao, notice: 'Qualificacao was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @qualificacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qualificacoes/1
  # DELETE /qualificacoes/1.json
  def destroy
    @qualificacao = Qualificacao.find(params[:id])
    @qualificacao.destroy

    respond_to do |format|
      format.html { redirect_to qualificacoes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/qualificacoes_helper.rb
module QualificacoesHelper
end

app/views/qualificacoes/_form.html.erb
<%= form_for(@qualificacao) do |f| %>
  <% if @qualificacao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@qualificacao.errors.count, "error") %> prohibited this qualificacao from being saved:</h2>

      <ul>
        <% @qualificacao.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <% if @qualificacao.cliente %>
    <%= f.hidden_field 'cliente_id' %>
    <% else %>
    <p><font color="darkgrey" size="6"><%= f.label :cliente_id %><br /></font>
    <%= f.collection_select(:cliente_id, Cliente.order('nome'), :id, :nome, {:prompt => true}) %></p>
<%end%>
  </div>

  <div class="field">
    <% if @qualificacao.restaurante %>
    <%= f.hidden_field 'restaurante' %>
    <%else%>
    <p><font color="darkgrey" size="6"><%= f.label :restaurante_id %><br /><font>
    <%= f.collection_select(:restaurante_id, Restaurante.order('nome'), :id, :nome, {:prompt => true}) %></p>
    <%end%>
  </div>

  <div class="field">
    <font color="darkgrey" size="6"><%= f.label :nota %><br /></font>
    <%= f.text_field :nota %>
  </div>
  <div class="field">
    <font color="darkgrey" size="6"><%= f.label :valor_gasto %><br /></font>
    <%= f.text_field :valor_gasto %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/qualificacoes/edit.html.erb
<h1 align="center"><font color="#9B1C26">Editing qualificacao</font></h1>

<table align="center" class="titulo2">
	<tr>
		<td align="center">
			<font size="6">
<%= render 'form' %>
			</font>
		</td>
	</tr>
</table>

<table align="center" class="titulo2">
	<td>
		<font size="6">
<%= link_to 'Mostrar', @qualificacao %> |
<%= link_to 'Voltar', qualificacoes_path %>
		</font>
	</td>
</table>

app/views/qualificacoes/index.html.erb
<h1 class="titulo" align="center"><font color="#9B1C26">Lista de Qualificacoes</h1>

<table align="center" width="80%">
 
  <br>
  <br>
  <br>

  <tr>
    <th><font color="#9B1C26" size="6" align="center">Cliente</font></th>
    <th><font color="#9B1C26" size="6" align="center">Restaurante</font></th>
    <th><font color="#9B1C26" size="6" align="center">Nota</font></th>
    <th><font color="#9B1C26" size="6" align="center">Valor gasto</font></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @qualificacoes.each do |qualificacao| %>
  <tr>
    <td><font color="darkgrey" size="6"><%= qualificacao.cliente.nome %></td>
    <td align="center"><font color="darkgrey" size="6"><%= qualificacao.restaurante.nome %></td>
    <td align="center"><font color="darkgrey" size="6"><%= qualificacao.nota %></td>
    <td align="center"><font color="darkgrey" size="6"><%= qualificacao.valor_gasto %></td>
    <td align="center"><font color="darkgrey" size="6"><%= link_to 'Mostrar', qualificacao %></td>
    <td align="center"><font color="darkgrey" size="6"><%= link_to 'Editar', edit_qualificacao_path(qualificacao) %></td>
    <td align="center"><font color="darkgrey" size="6"><%= link_to 'Remover', qualificacao, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
  </tr>
<% end %>
</table>

<br>
<br>
<br>
<y align="center" class="fonte">
<center><%= paginate @qualificacoes %>
</y>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<font class="novo" size="6">
  <!--<%= link_to 'Novo', action: 'new' %>-->

<a class="bt" href="http://localhost:3000/qualificacoes/new" title="Nova Qualificação">
  <font color="white">Nova Qualificação</font>
</a>  
</font>

app/views/qualificacoes/new.html.erb
<h1 align="center" class="titulo"><font color="#9B1C26">New qualificacao</font></h1>

<br>

<table align="center">
	<tr>
		<td align="center">
			<font size="6">
<%= render 'form' %>
			</font>
		</td>
	</tr>
</table>

<br>
<br>
<br>

<table align="center">
	<td>
		<font size="6">
<%= link_to 'Voltar', qualificacoes_path %>
		</font>
	</td>
</table>

app/views/qualificacoes/show.html.erb
<p id="notice"><%= notice %></p>

<table align="center">
	<tr>
		<td>
			<font size="6">
<p>
  <b><font color="#9B1C26">Cliente:</font></b>
  <font color="grey"><%= @qualificacao.cliente_id %></font>
</p>

<p>
  <b><font color="#9B1C26">Restaurante:</font></b>
  <font color="grey"><%= @qualificacao.restaurante_id %></font>
</p>

<p>
  <b><font color="#9B1C26">Nota:</font></b>
  <font color="grey"><%= @qualificacao.nota %></font>
</p>

<p>
  <b><font color="#9B1C26">Valor gasto:</font></b>
  <font color="grey"><%= @qualificacao.valor_gasto %></font>
</p>
			</font>
		</td>
	</tr>
</table>

<table align="center" class="titulo2">
	<tr>
		<td>
			<font size="6">
<%= link_to "Nova qualificacao", :controller => 'qualificacoes', 
:action => "new",
:cliente => @cliente %>
			</font>
		</td>
	</tr>
</table>

<table align="center" class="titulo2">
	<tr>
		<td>
			<font size="6" style="text-decoration:none">
<%= novo_comentario(@qualificacao) %>
			</font>
		</td>
	</tr>
</table>

<table align="center" class="titulo2">
	<td>
		<font size="6">
<%= link_to 'Editar', edit_qualificacao_path(@qualificacao) %> |
<%= link_to 'Voltar', qualificacoes_path %>
		</font>
	</td>
</table>


<% unless @qualificacao.comentarios.empty?%>
<%= comentarios @qualificacao %>
<%end%>